### PR TITLE
Use _EXPORTED_TARGETS target suffix instead of _generate_messages_cpp

### PR DESCRIPTION
**Pull request by esteve**
_EXPORTED_TARGETS target suffix is preferred over _generate_messages_cpp, see https://github.com/ros/catkin_tutorials/issues/6

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by dirk-thomas** [comment]
There is a clear performance trade off. Arguably we can decide to use the exported targets variable since it is tutorial code.

**Comment by esteve** [comment]
@dirk-thomas true, but I thought that it's best to teach about the most generic way of generating messages (plus all the other possible targets in EXPORTED_TARGETS) and then explain what's the most efficient one later.

**Comment by stonier** [comment]
+1

**Pull request merged**
