### PR TITLE
class_loader dependency is added to nodelet_tutorial_math package

### PR DESCRIPTION
**Pull request by muratsevim**
Fixes the undefined symbol errors when linking libnodelet_math library on Mac OS X

### CODE REVIEW

**Comment by wjwwood** [comment]
What version of ROS? This was fixed upstream in Hydro. AFAIK.

**Comment by muratsevim** [comment]
Oh! I was working with Groovy. So will linking work in Hydro without adding the dependency? If yes, is there an easy way to get the fix without completely moving to Hydro?

**Comment by wjwwood** [comment]
@muratsevim I think the fix is in pluginlib, let me see if I can find it.

**Comment by wjwwood** [comment]
Nope, it was in `nodelet`:

https://github.com/ros/nodelet_core/commit/70f4e26e399c6b211d51f04113014a9b880c3f11

**Comment by wjwwood** [comment]
I can probably backport it, or you can just apply the patch manually.

This is the important change here:

https://github.com/ros/nodelet_core/commit/70f4e26e399c6b211d51f04113014a9b880c3f11#L0R19

**Comment by wjwwood** [comment]
Adding it here is actually incorrect, as this package doesn't directly use `class_loader`, the fact that you need `class_loader` here is an implementation detail of `pluginlib`.

**Comment by wjwwood** [comment]
Thanks for pointing it out, I'll probably do the backport, but I can't say when we'll release `nodelet_core` for Groovy again.

**Comment by muratsevim** [comment]
Thanks! That helped a lot and probably saved me from adding the dependency to other packages. I will remove the dependency on nodelet_tutorial_math and apply the patch manually.

**Comment by wjwwood** [comment]
https://github.com/ros/nodelet_core/issues/6

**Comment by wjwwood** [comment]
I went ahead and released `nodelet_core`, so you should be able to get the new released version 0.7.16 too.

https://github.com/ros/rosdistro/pull/1533

**Pull request closed without merging**
