### PR TITLE
add sample code to access the action result for fibonacci.

### PR DESCRIPTION
**Pull request by fujitatomoya**
really easy fix, showing how to access the action result for users.

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@clalancette 

can you take a look at this?

**Comment by clalancette** [comment]
It seems reasonable to me, but @stonier is the maintainer here and this would need buy-in from him.

**Comment by fujitatomoya** [comment]
@stonier 

this is an easy example code, could you take a look at it?

**Comment by stonier** [comment]
LGTM.

**Comment by stonier** [comment]
Cherry-picked to `noetic-devel`.

**Pull request merged**
